config/routes.rb
Rails.application.routes.draw do
  get 'routes/sub' => 'routes#sub'
  post 'routes/sub' => 'routes#sub'
  resources :routes

end

app/models/route.rb
class Route < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/routes_controller.rb
require 'json'
require 'time'
require 'uri'


class RoutesController < ApplicationController
  before_action :set_route, only: [:show, :edit, :update, :destroy]

  # GET /routes
  # GET /routes.json
  def index
    if (params.keys.size >= 8)
      # get param
      p = params
      from = p["from"]
      to = p["to"]
      y = p["y"]
      m = p["m"]
      d = p["d"]
      hour = p["hh"]
      min = p["mm"]
      # TODO: 再度、到着出発の部分のフラグを見直し
      leave_reach = p["lr"] == "l" ? 0 : 1

      # TODO: mの前の0を直す
      uri=URI.escape("http://api-gifubus.herokuapp.com/v1?date=#{y}/0#{m}/#{d}&time=#{hour.to_s+min.to_s}&start_arrive=#{leave_reach}&start_name=#{from}&arrive_name=JR岐阜")

      uri = URI.parse(uri)
      json = Net::HTTP.get(uri)
      result = JSON.parse(json)


      @bus_first=result["data"].first
      bus_arrive=result["data"].first["info"].last["arrive_time"]

      bus_arrivetime=Time.parse(bus_arrive)
      bus_arrivetime=bus_arrivetime+300

      jrstart_hour=bus_arrivetime.hour
      jrstart_min=bus_arrivetime.min

      # TODO: 岐阜　→ 名古屋の逆区間も対応
      jr_route = Transfer::Jr::search("岐阜", "名古屋", y, m, d, jrstart_hour, jrstart_min, "出発")
      @jr_route = jr_route.size > 0 ? jr_route.first : nil

    else
      # TODO: 何もないときは、リストを出さない
      uri=URI.escape('http://api-gifubus.herokuapp.com/v1?date=2015/01/14&time=1605&start_arrive=0&start_name=繰舟橋&arrive_name=下佐波')
      uri = URI.parse(uri)
      json = Net::HTTP.get(uri)
      result = JSON.parse(json)

      @bus_first=result["data"].first
      bus_arrive=result["data"].first["info"].last["arrive_time"]

      bus_arrivetime=Time.parse(bus_arrive)
      bus_arrivetime=bus_arrivetime+300

      jrstart_hour=bus_arrivetime.hour
      jrstart_min=bus_arrivetime.min

      @result2=Transfer::Jr::search("岐阜", "名古屋", 2015, 1, 14, jrstart_hour, jrstart_min, "出発")


      @routes = Route.all
      jr_routes = Transfer::Jr::search(from="岐阜", to="名古屋", 2015, 6, 14, hour=10, min=00, "出発")
      @jr_route = jr_routes.size > 0 ? jr_routes.first : nil
    end
  end

  # TODO: いらないsubの部分は消す
  def sub
    @origin_bus="岐阜大学"
    @dest_bus="JR岐阜"
    @origin_station="岐阜"
    @dest_station="名古屋"

    uri=URI.escape('http://api-gifubus.herokuapp.com/v1?date=2015/01/14&time=1605&start_arrive=0&start_name=繰舟橋&arrive_name=下佐波')

    # uri=URI.escape('http://api-gifubus.herokuapp.com/v1?date=2015/01/14&time=1605&start_arrive=0&start_name=岐阜大学&arrive_name=JR岐阜')
    uri = URI.parse(uri)
    json = Net::HTTP.get(uri)
    result = JSON.parse(json)


    @bus_first=result["data"].first
    @bus_last=result["data"].first["info"].last

    bus_arrive=result["data"].first["info"].last["arrive_time"]

    bus_arrivetime=Time.parse(bus_arrive)
    bus_arrivetime=bus_arrivetime+300

    jrstart_hour=bus_arrivetime.hour
    jrstart_min=bus_arrivetime.min

    @result2=Transfer::Jr::search("岐阜", "名古屋", 2015, 1, 14, jrstart_hour, jrstart_min, "出発")
  end

  # GET /routes/1
  # GET /routes/1.json
  def show
  end

  # GET /routes/new
  def new
    @route = Route.new
  end

  # GET /routes/1/edit
  def edit
  end

  # POST /routes
  # POST /routes.json
  def create
    @route = Route.new(route_params)

    respond_to do |format|
      if @route.save
        format.html { redirect_to @route, notice: 'Route was successfully created.' }
        format.json { render :show, status: :created, location: @route }
      else
        format.html { render :new }
        format.json { render json: @route.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /routes/1
  # PATCH/PUT /routes/1.json
  def update
    respond_to do |format|
      if @route.update(route_params)
        format.html { redirect_to @route, notice: 'Route was successfully updated.' }
        format.json { render :show, status: :ok, location: @route }
      else
        format.html { render :edit }
        format.json { render json: @route.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /routes/1
  # DELETE /routes/1.json
  def destroy
    @route.destroy
    respond_to do |format|
      format.html { redirect_to routes_url, notice: 'Route was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_route
      @route = Route.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def route_params
      params.require(:route).permit(:content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/routes_helper.rb
module RoutesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Transfer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css"/>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/routes/_form.html.erb
<%= form_for(@route) do |f| %>
  <% if @route.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@route.errors.count, "error") %> prohibited this route from being saved:</h2>

      <ul>
      <% @route.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/routes/edit.html.erb
<h1>Editing Route</h1>

<%= render 'form' %>

<%= link_to 'Show', @route %> |
<%= link_to 'Back', routes_path %>

app/views/routes/index.html.erb
<style>
    .bg-primary {
        padding: 15px;
        margin: 0px;
    }

    .bs-callout-info {
        border-left-color: #1B809E !important;
    }

    .bs-callout {
        padding: 20px;
        border-width: 1px 1px 1px 5px;
        border-style: solid;
        border-color: #EEE;
        -moz-border-top-colors: none;
        -moz-border-right-colors: none;
        -moz-border-bottom-colors: none;
        -moz-border-left-colors: none;
        border-image: none;
        border-radius: 3px;
    }

    .bs-callout-wp {
        padding-left: 3%;
        margin-bottom: 10px;
    }

    .route-detail {
        margin-bottom: 20px;
    }

    .form {
        background-color: lightgray;
        padding: 15px;
    }

</style>

<p id="notice"><%= notice %></p>

<div class="form">

    <h1>乗り換え検索</h1>
    <form action="/routes" accept-charset="UTF-8" method="get">
        <div class="form-group">
            <label>from</label>
            <input name="from" class="form-control" placeholder="from">
        </div>
        <div class="form-group">
            <label>to</label>
            <input name="to" class="form-control" placeholder="to">
        </div>
        <p>
            <select name="y">
                <% for i in 0..2 %>
                    <option value="<%= Time.now.year + i %>"><%= Time.now.year + i %></option>
                <% end %>
            </select> 月

            <select name="m">
                <% for i in 1..12 %>
                    <option value="<%= i %>"><%= i %></option>
                <% end %>
            </select> 月
            <select name="d">
                <% for i in 1..31 %>
                    <option value="<%= i %>"><%= i %></option>
                <% end %>
            </select> 日
        </p>
        <p>
            <select name="hh">
                <% for i in 0..23 %>
                    <option value="<%= i %>"><%= i %></option>
                <% end %>
            </select> 時
            <select name="mm">
                <% for i in 0..59 %>
                    <% if i % 5 == 0 %>
                        <option value="<%= i %>"><%= i %></option>
                    <% end %>
                <% end %>
            </select> 分
            <select name="lr">
                <option value="l">出発</option>
                <option value="r">到着</option>
            </select>
        </p>
        <p>
            <label class="radio-inline">
                <input type="radio" name="inlineRadioOptons" id="inlineRadio1" value="option1"> 指定時刻
            </label>
            <label class="radio-inline">
                <input type="radio" name="inlineRadioOptions" id="inlineRadio2" value="option2"> 始発
            </label>
            <label class="radio-inline">
                <input type="radio" name="inlineRadioOptions" id="inlineRadio3" value="option3"> 終電
            </label>
        </p>
        <button type="submit" class="btn btn-default">検索</button>
    </form>
</div>

<div class="route">
    <!-- TODO: 全体の数値を計算 -->
    <h2>14:15 発 → 15:35発 </h2>
    <h3>(時間: 60分 料金: 400円)</h3>

    <!-- TODO: bus_firstがない場合はよしなに処理する -->
    <!-- 岐阜バスの検索 -->
    <% @bus_first["info"].each do |info| %>
        <div class="route-detail">
            <p class="bg-primary"><%= info["start_name"]%> (<%= info["start_time"] %>) <%= info["fare"] %>

            <p>

            <div class="bs-callout-wp">
                <div class="bs-callout bs-callout-info" id="callout-help-text-accessibility">
                    <p>
                        <%= info["details"].first %>
                    </p>
                </div>
            </div>
            <p class="bg-primary"><%= info["arrive_name"] %> (<%= info["arrive_time"] %>)

            <p>
        </div>
    <% end %>
    <!-- JRの検索 -->
    <% if !@jr_route.nil? %>
        <div class="route-detail">
            <p>(時間: <%= @jr_route[:min] %> 料金: <%= @jr_route[:fare] %>)</p>
            <% stations = @jr_route[:route_details][:stations] %>
            <p class="bg-primary"><%= stations[0][:name] %> <%= stations[0][:time] %>

            <p>

            <div class="bs-callout-wp">
                <div class="bs-callout bs-callout-info" id="callout-help-text-accessibility">
                    <p>
                        <%= @jr_route[:route_details][:transport] %> (<%= @jr_route[:route_details][:between] %>)
                    </p>
                </div>
            </div>
            <p class="bg-primary"><%= stations[1][:name] %> <%= stations[1][:time] %>
            <p>
        </div>
    <% end %>
</div>

app/views/routes/new.html.erb
<h1>New Route</h1>

<%= render 'form' %>

<%= link_to 'Back', routes_path %>

app/views/routes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @route.content %>
</p>

<%= link_to 'Edit', edit_route_path(@route) %> |
<%= link_to 'Back', routes_path %>

app/views/routes/sub.html.erb
<p id="notice"><%= notice %></p>

<h1>Routes Result</h1>
<h3>再検索</h3>

<form>
      <div class="form-group">
        <label for="exampleInputEmail1">from</label>
          <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Origin">
      </div>
      <div class="form-group">
          <label for="exampleInputPassword1">to</label>
          <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Destination">
      </div>
      <button type="submit" class="btn btn-default">検索</button>
</form>

<dl class="dl-horizontal">
  <dt>バス運賃</dt><dd><%=@bus_first["price"]%></dd>

  <hr>

  <% @bus_first["info"].each do |info| %>
      <dt>バス出発時刻</dt><dd><%= info["start_time"] %></dd>
      <dt>バス到着時刻</dt><dd><%= info["arrive_time"] %></dd>
      <dt>出発駅</dt><dd><%= info["start_name"] %></dd>
      <dt>到着駅</dt><dd><%= info["arrive_name"] %></dd>
      <dt>バス運賃</dt><dd><%= info["fare"] %></dd>
      <dt>バス路線</dt><dd><%= info["details"].first %></dd>
      <hr>
  <% end %>
</dl>